2021-07-14 02:06:31,270 [<ipython-input-1-35521dce9a68> | 49] INFO: Start to run instance_1
2021-07-14 02:06:31,271 [simulate_api.py | 60] INFO: Start time of the simulator: 2021-07-14 00:00:00, time interval:  600.00
2021-07-14 02:06:31,285 [input_utils.py  | 48] INFO: Get 154 factories
2021-07-14 02:06:32,950 [input_utils.py  | 52] INFO: Get 23562 routes
2021-07-14 02:06:32,969 [input_utils.py  | 57] INFO: Get 5 vehicles
2021-07-14 02:06:32,978 [input_utils.py  | 61] INFO: Get 50 orders
2021-07-14 02:06:32,979 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2021-07-14 02:06:32,982 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2021-07-14 02:06:32,982 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2021-07-14 02:06:32,983 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2021-07-14 02:06:32,984 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2021-07-14 02:06:32,985 [simulate_environment.py | 99] INFO: **************************************************
2021-07-14 02:06:32,986 [simulate_environment.py | 103] INFO: cur time: 2021-07-14 00:10:00, pre time: 2021-07-14 00:00:00
2021-07-14 02:06:32,986 [simulate_environment.py | 140] INFO: Start to update the input of 2021-07-14 00:10:00
2021-07-14 02:06:32,988 [simulate_environment.py | 167] INFO: Get 1 unallocated order items, 0 ongoing order items, 0 completed order items
2021-07-14 02:06:35,556 [simulate_environment.py | 245] ERROR: 2021-07-14 02:06:35,509 [main_algorithm.py | 31] ERROR: Failed to run algorithm
2021-07-14 02:06:35,510 [main_algorithm.py | 32] ERROR: Error: local variable 'save_pack_id_to_same_oreder' referenced before assignment, Traceback (most recent call last):
  File "main_algorithm.py", line 28, in <module>
    scheduling()
  File "c:\Users\hp\Desktop\华为竞赛\ALGO\Huawei competition\7.12\algorithm\new_algorithm.py", line 812, in scheduling
    vehicle_id_to_destination, vehicle_id_to_planned_route = dispatch_orders_to_vehicle(id_to_factory, id_to_unallocated_order_item,
  File "c:\Users\hp\Desktop\华为竞赛\ALGO\Huawei competition\7.12\algorithm\new_algorithm.py", line 741, in dispatch_orders_to_vehicle
    for x_id,x in save_pack_id_to_same_oreder.items():
UnboundLocalError: local variable 'save_pack_id_to_same_oreder' referenced before assignment

FAIL

2021-07-14 02:06:35,557 [simulate_environment.py | 246] ERROR: Can not catch the 'SUCCESS' from the algorithm. 未寻获算法输出成功标识'SUCCESS'。
